### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by cbix** [CICM/HoaLibrary-Faust#3]
I noticed that the hoa.lib within the official [faustlibraries](https://github.com/grame-cncm/faustlibraries) is based on this code but states an LGPL+exception license, which is not compatible with the GPL that's mentioned here in README.md.
In fact, the strong copyleft of GPL, when used in a library that's supposed to be statically linked (which faust does), would enforce the use of the GPL on every work that uses it, even non-commercial open-source projects.

Maybe all this has been discussed already back when including hoa.lib into faust, but especially the license difference could be clarified here :)

**Comment by pierreguillot** [comment]
You can use the license faustlibraries license. This repository has not been updated since a while and we should make it consistent with faust... sorry

**Comment by pan-athen** [comment]
I'm working on a commercial web player for ambisonics, and in general, I use Faust to create some necessary routing because I feel comfortable with the development framework. I export my work from the Faust IDE into Web Assembly or JS code to integrate it with my product. @pierreguillot can you please clarify if it's ok to do that for commercial work or do I have to secure a separate license for your HOA library? Thanks in advance for your time and kind help! :-)

**Comment by pierreguillot** [comment]
Idem. You should consider the Faust library license.
